name: Cypress Test
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run
         browser: chrome
       env:
         CYPRESS_email: trilles.ficticio@gmail.com
         CYPRESS_password: Ficticio1234
         CYPRESS_nickname: trilles.02368525